export enum Action {
    COMPARE_ROLLINGS = 'COMPARE_ROLLINGS',
    STREAM_BUFFERS = 'STREAM_BUFFERS',
    PREPARE_STREAM = 'PREPARE_STREAM',
    CLOSE_CONNECTION = 'CLOSE_CONNECTION',
    STREAM_START = 'STREAM_START',
    REMOVE_FILE = 'REMOVE_FILE',
    REMOVE_DIR = 'REMOVE_DIR',
    ADD_DIR = 'ADD_DIR',
    ADD_FILE = 'ADD_FILE',
    ERROR = 'ERROR'
}

